adm/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from adm.views import (
    UserAuthView,
    UserCategoryListView,
    OfficeView,
    OfficeUpdateView,
    UserDetailChangeView,
    UserDetailView,
    MyCase,
    CaseCategory,
    CaseInfo,
    CaseDistributeView,
    CaseDoingListView,
    CaseSearchListView)

urlpatterns = [
    url(r'^user_auth/$', UserAuthView.as_view(), name="user-auth"),
    url(r'^user_category_list/$', UserCategoryListView.as_view(), name="user-category-list"),
    url(r'^user_detail_change/$', UserDetailChangeView.as_view(), name="user-detail-change"),
    url(r'^user_detail/(?P<pk>\d+)/$', UserDetailView.as_view(), name="user-detail"),
    url(r'^office/$', OfficeView.as_view(), name="office"),
    url(r'^office_update/(?P<pk>\d+)/$', OfficeUpdateView.as_view(), name="office-update"),

    url(r'^my_case/$', MyCase.as_view(), name="my-case"),
    url(r'^case_category/$', CaseCategory.as_view(), name="case-category"),

    url(r'^case_info/$', CaseInfo.as_view(), name="case-info"),
    url(r'^case_distrib_list/$', CaseDistributeView.as_view(), name="case-distrib-list"),
    url(r'^case_doing_list/$', CaseDoingListView.as_view(), name="case-doing-list"),
    url(r'^case_search_list/$', CaseSearchListView.as_view(), name="case-search-list"),

]

advisor/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from adm.views import UserAuthView, UserCategoryListView, OfficeView, OfficeUpdateView
from advisor.views import ConsultPanelView, ConsultUnitView, ConsultUnitListView, ConsultUnitUpdateView, \
    ConsultUnitDeleteView, ConsultUnitDispatchView

urlpatterns = [
    url(r'^advisor_panel/$', ConsultPanelView.as_view(), name="advisor-panel"),
    url(r'^consult_unit_add/$', ConsultUnitView.as_view(), name="consult-unit-add"),
    url(r'^consult_unit_list/$', ConsultUnitListView.as_view(), name="consult-unit-list"),
    url(r'^consult_unit_update/(?P<pk>\d+)/$', ConsultUnitUpdateView.as_view(), name="consult-unit-update"),
    url(r'^consult_unit_delete/(?P<pk>\d+)/$', ConsultUnitDeleteView.as_view(), name="consult-unit-delete"),
    url(r'^consult_unit_dispatch/$', ConsultUnitDispatchView.as_view(), name="consult-unit-dispatch"),
    # url(r'^office_update/(?P<pk>\d+)/$', OfficeUpdateView.as_view(), name="office-update"),
]

lawyer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.authtoken import views

from rbac.account import login, logout, password_change

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^password/change/(?P<pk>\d+)/$', password_change, name='password-change'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^api-token-auth/', views.obtain_auth_token, name="obtain-auth-token"),
    url(r'^rbac/', include('rbac.urls', namespace='rbac')),
    url(r'^adm/', include('adm.urls', namespace='adm')),
    url(r'^adm/api/', include('adm.api.urls')),
    url(r'^advisor/', include('advisor.urls', namespace='advisor')),
    url(r'^calculator/', include('calculator.urls', namespace='calculator')),
    url(r'^calculator/api/', include('calculator.api.urls', namespace='calculator-api')),
    url(r'^calc_manager/', include('calculator.calculator_urls', namespace='calc-mgr')),
    url(r'^civil/', include('civilcase.urls', namespace='civil-case')),
    url(r'^criminal/', include('crimicase.urls', namespace='criminal')),
    url(r'^admincase/', include('admincase.urls', namespace='admincase')),
    url(r'^private/', include('crimiprivate.urls', namespace='private')),
    url(r'^crmcivil/', include('crimicivil.urls', namespace='crmcivil')),
    url(r'^print/', include('civilcase.print_urls', namespace='print')),
    url(r'^civil/api/', include('civilcase.api.urls', namespace='civil-api')),
]

advisor/models.py
from django.db import models

from baseinfo.constants import IS_ASSIGN
from rbac.models import UserInfo


class ConsultantUnit(models.Model):
    """顾问单位"""
    SCHEME = (
        (1, '方案A'),
        (2, '方案B'),
        (3, '方案C'),
        (4, '方案D'),
    )
    TYPE = (
        (0, '企业'),
        (1, '个人'),
    )
    unit_name = models.CharField(verbose_name="企业名称/姓名", max_length=120)
    unit_type = models.IntegerField(verbose_name="类型", choices=TYPE, default=0)
    person = models.CharField(verbose_name="联系人员", max_length=64, blank=True, default="")
    sign_begin = models.DateField(verbose_name="签约开始时间")
    sign_end = models.DateField(verbose_name="截止时间")
    telephone = models.CharField(verbose_name="联系电话", max_length=32)
    scheme = models.IntegerField(verbose_name="签约方案", choices=SCHEME)
    address = models.CharField(verbose_name="地址", max_length=120)
    lawyer = models.ManyToManyField(verbose_name="律师姓名", to=UserInfo, blank=True)
    is_assign = models.IntegerField(verbose_name="分配确认", choices=IS_ASSIGN, blank=True, null=True)
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    def __str__(self):
        return self.unit_name

    class Meta:
        verbose_name = "顾问单位"
        verbose_name_plural = verbose_name

    def get_lawyer_list(self):
        lawyer_list = []
        for user in self.lawyer.all():
            lawyer_list.append(user.real_name)
        print(lawyer_list)
        return ",".join(lawyer_list)

advisor/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django import forms

from rbac.models import UserInfo, Post
from .models import ConsultantUnit


class ConsultantUnitForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id', None)
        super(ConsultantUnitForm, self).__init__(*args, **kwargs)
        # self.fields['lawyer'].queryset = UserInfo.objects.all()
        # if user_id:
        #     self.fields['lawyer'].queryset = UserInfo.objects.filter(pk=user_id)

    class Meta:
        model = ConsultantUnit
        fields = ["unit_name", "person", "unit_type", "sign_begin", "sign_end", "telephone", "scheme", "address", "lawyer", "is_assign"]

        widgets = {
            'unit_name': forms.TextInput(attrs={'class': "form-control", 'placeholder': '请输入企业名称'}),
            'person': forms.TextInput(attrs={'class': "form-control", 'placeholder': '请输入联系人员'}),
            'sign_begin': forms.TextInput(attrs={'class': "form-control", 'placeholder': '请输入签约开始时间'}),
            'sign_end': forms.TextInput(attrs={'class': "form-control", 'placeholder': '请输入签约结束时间'}),
            'telephone': forms.TextInput(attrs={'class': "form-control", 'placeholder': '请输入联系电话'}),
            'unit_type': forms.Select(attrs={'class': "form-control", 'placeholder': '请选择类型方案'}),
            'scheme': forms.Select(attrs={'class': "form-control", 'placeholder': '请选择签约方案'}),
            'address': forms.TextInput(attrs={'class': "form-control", 'placeholder': '请输入单位地址'}),
            'lawyer': forms.CheckboxSelectMultiple(attrs={'class': "checkbox list-inline"}),
            'is_assign': forms.Select(attrs={'class': "form-control"}),
        }

advisor/views.py
import datetime

from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from advisor.forms import ConsultantUnitForm
from advisor.models import ConsultantUnit
from lawyer import settings


class ConsultPanelView(View):
    """顾问功能面板"""
    def get(self, request, *args, **kwargs):
        current_permission_pid = request.current_permission_pid
        menu_dict = request.session.get(settings.MENU_SESSION_KEY)
        menu = menu_dict.get(str(current_permission_pid), None)

        if menu:
            children_menus = menu.get("children", None)
        else:
            children_menus = None
        print(children_menus)
        return render(request, template_name="advisor/advisor_panel.html", context={"children_menus": children_menus})

    def post(self, request, *args, **kwargs):
        pass


class ConsultUnitView(View):
    """顾问单位增加"""
    def get(self, request, *args, **kwargs):
        # form = ConsultantUnitForm(user_id=request.session.get("user_id"))
        form = ConsultantUnitForm()
        return render(request, template_name="advisor/advisor_add.html", context={"form": form})

    def post(self, request, *args, **kwargs):
        form = ConsultantUnitForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("advisor:consult-unit-add"))

        return render(request, template_name="advisor/advisor_add.html", context={"form": form})


class ConsultUnitListView(View):
    """顾问单位查询"""
    def get(self, request, *args, **kwargs):
        unit_name = request.GET.get("unit_name", None)
        person = request.GET.get("person", None)
        begin_time = request.GET.get("begin_time", None)
        end_time = request.GET.get("end_time", None)
        user_id = request.session.get("user_id", None)
        post = request.session.get("post", None)
        is_superuser = request.session.get("is_superuser", 0)
        if post in [5, 7] or is_superuser == 1:
            consultants = ConsultantUnit.objects.all()
        else:
            consultants = ConsultantUnit.objects.filter(lawyer__id=user_id)

        if unit_name:
            consultants = consultants.filter(unit_name__contains=unit_name)

        if person:
            consultants = consultants.filter(person__contains=person)

        if begin_time and not end_time:
            begin_date = datetime.datetime.strptime(begin_time, "%Y-%m-%d")
            consultants = consultants.filter(sign_begin=begin_date)

        if begin_time and end_time:
            begin_date = datetime.datetime.strptime(begin_time, "%Y-%m-%d")
            end_date = datetime.datetime.strptime(end_time, "%Y-%m-%d")
            consultants = consultants.filter(sign_begin__range=(begin_date, end_date))

        consultants = consultants.order_by("-sign_begin")
        # print(consultants)
        context = {
            "consultants": consultants
        }
        return render(request, template_name="advisor/consult_unit_list.html", context=locals())

    def post(self, request, *args, **kwargs):
        pass


class ConsultUnitUpdateView(View):
    """顾问单位修改"""
    def get(self, request, *args, **kwargs):
        c_id = kwargs.get("pk", None)
        format = request.GET.get("_format", None)
        print("c_id", c_id)
        if c_id:
            consult_unit = ConsultantUnit.objects.filter(pk=c_id).first()
            if consult_unit:
                form = ConsultantUnitForm(instance=consult_unit)
                if format == "html":
                    return render(request, template_name="advisor/include/consult_unit_detail.html", context={"form": form, "format": format})
                return render(request, template_name="advisor/advisor_add.html", context={"form": form})
        else:
            pass
        return redirect(reverse("advisor:consult-unit-list"))

    def post(self, request, *args, **kwargs):
        c_id = kwargs.get("pk")
        format = request.POST.get("format", None)
        if c_id:
            consult_unit = ConsultantUnit.objects.filter(pk=c_id).first()
            form = ConsultantUnitForm(request.POST, instance=consult_unit)
            if form.is_valid():
                form.save()
            else:
                return render(request, template_name="advisor/advisor_add.html", context={"form": form})
        if format == "html":
            return redirect(reverse("advisor:consult-unit-dispatch"))   # 单位分配

        return redirect(reverse("advisor:consult-unit-list"))


class ConsultUnitDeleteView(View):
    """顾问单位删除"""
    def get(self, request, *args, **kwargs):
        c_id = kwargs.get("pk")
        if c_id:
            ConsultantUnit.objects.filter(pk=c_id).delete()
        else:
            pass

        return redirect(reverse("advisor:consult-unit-list"))


class ConsultUnitDispatchView(View):
    """顾问单位分配"""
    def get(self, request, *args, **kwargs):
        units = ConsultantUnit.objects.filter(Q(is_assign=0) | Q(is_assign__isnull=True), unit_type=0)
        persons = ConsultantUnit.objects.filter(Q(is_assign=0) | Q(is_assign__isnull=True), unit_type=1)
        context = {
            "units": units,
            "persons": persons,
        }
        return render(request, template_name="advisor/unit_dispach_list.html", context=context)

    def post(self, request, *args, **kwargs):
        pass

advisor/templates/advisor/advisor_add.html
{% extends 'rbac/base.html' %}{% load static rbac %}
{% block title %}用户授权{% endblock title %}
{% block right %}
  <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
            <div class="panel panel-default mgt">
                <div class="panel-heading">
                    <h3 class="panel-title text-center" style="font-size: 24px;">顾问单位维护</h3>
                </div>
                <div class="panel-body">
                    {% if form %}
                        <form class="form-horizontal" method="post">
                        {% csrf_token %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="id_unit_name"><span class="red">*</span>{{ form.unit_name.label }}</label>
                                <div class="col-sm-4">
                                    {{ form.unit_name}}
                                    <span class="text-danger">{{ form.unit_name.errors.0 }}</span>
                                </div>
                                <label class="col-sm-2 control-label" for="id_unit_type"><span class="red">*</span>{{ form.unit_type.label }}</label>
                                <div class="col-sm-4">
                                     {{ form.unit_type }}
                                    <span class="text-danger">{{ form.unit_type.errors.0 }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="id_telephone"><span class="red">*</span>{{ form.telephone.label }}</label>
                                <div class="col-sm-4">
                                     {{ form.telephone }}
                                    <span class="text-danger">{{ form.telephone.errors.0 }}</span>
                                </div>
                                <label class="col-sm-2 control-label" for="id_person">{{ form.person.label }}</label>
                                <div class="col-sm-4">
                                     {{ form.person }}
                                    <span class="text-danger">{{ form.person.errors.0 }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"
                                       for="id_sign_begin"><span class="red">*</span>{{ form.sign_begin.label }}</label>
                                <div class="col-sm-4">
                                    {{ form.sign_begin }}
                                    <span class="text-danger">{{ form.sign_begin.errors.0 }}</span>
                                </div>
                                <label class="col-sm-2 control-label" for="id_sign_end"><span class="red">*</span>{{ form.sign_end.label }}</label>
                                <div class="col-sm-4">
                                    {{ form.sign_end }}
                                    <span class="text-danger">{{ form.sign_end.errors.0 }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="id_scheme"><span
                                        class="red">*</span>{{ form.scheme.label }}</label>
                                <div class="col-sm-4">
                                    {{ form.scheme }}
                                    <span class="text-danger">{{ form.scheme.errors.0 }}</span>
                                </div>
                                <label class="col-sm-2 control-label"
                                       for="id_sign_begin"><span class="red">*</span>{{ form.address.label }}</label>
                                <div class="col-sm-4">
                                    {{ form.address }}
                                    <span class="text-danger">{{ form.address.errors.0 }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"
                                       for="id_sign_begin"><span class="red">*</span>{{ form.lawyer.label }}</label>
                                <div class="col-sm-10">
                                    {{ form.lawyer }}
                                    <span class="text-danger">{{ form.lawyer.errors.0 }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12 text-center">
                                    <button type="submit" class="btn btn-primary">保存</button>
                                </div>
                            </div>
                        </form>
                    {% endif %}
                    <div class="container-fluid" style="margin-top: 30px;padding:10px;">
                        <div class="col-sm-12 ">
                            <img src="{% static 'lawyer/img/sfb.jpg' %}" class="img-responsive center-block"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock right %}

{% block extjs %}
    <script>
    $(function () {
        $("#id_sign_begin, #id_sign_end").datepicker({
            format: "yyyy-mm-dd",
            language: "zh-CN",
            autoclose: true,
        });
    })

    </script>
{% endblock %}

advisor/templates/advisor/advisor_panel.html
{% extends 'rbac/base.html' %}{% load static rbac %}
{% block title %}用户授权{% endblock title %}
{% block right %}
    {% for item in children_menus %}
        {% if item.is_menu %}
        <div class="ynbox">
            <div class="ynntowbox"><a href="{{ item.url }}"><img
                    src="{% static item.icon %}"></a></div>
            <div class="ynname"><a href="{{ item.url }}">{{ item.title }}</a></div>
        </div>
        {% endif %}
    {% endfor %}

{#    <div class="ynbox">#}
{#        <div class="ynntowbox"><a href="{% url 'advisor:consult-unit-add' %}"><img#}
{#                src="{% static 'lawyer/img/fpgwdw.jpg' %}"></a></div>#}
{#        <div class="ynname"><a href="{% url 'advisor:consult-unit-add' %}">新建顾问单位</a></div>#}
{#    </div>#}
{#    <div class="ynbox">#}
{#        <div class="ynntowbox"><a href="{% url 'advisor:consult-unit-list' %}"><img#}
{#                src="{% static 'lawyer/img/fpgwdw.jpg' %}"></a></div>#}
{#        <div class="ynname"><a href="{% url 'advisor:consult-unit-list' %}">分配法律顾问</a></div>#}
{#    </div>#}
{#    <div class="ynbox">#}
{#        <div class="ynntowbox"><a href="{% url 'advisor:consult-unit-list' %}"><img#}
{#                src="{% static 'lawyer/img/cxgwdw.jpg' %}"></a></div>#}
{#        <div class="ynname"><a href="{% url 'advisor:consult-unit-list' %}">查询顾问单位</a></div>#}
{#    </div>#}

{% endblock right %}

advisor/templates/advisor/consult_unit_list.html
{% extends 'rbac/base.html' %}{% load static rbac%}
{% block title %} 顾问单位查询 {% endblock title %}
{% block css %}
    <style>
        .mgt{
           margin-top: 20px;
        }
        .panel-heading{
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            overflow: hidden;
        }
    </style>
{% endblock %}
{% block right %}
    <div class="row">
        <div class="container-fluid mgt">
            <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-ex">
                            <form class="form-inline" method="get">
                                <div class="form-group">
                                    <label class="sr-only" for="id_unit_name">企业名称</label>
                                    <input type="text" class="form-control" id="id_unit_name" name="unit_name" value="{{ unit_name|default:"" }}" placeholder="企业名称">
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="id_person">联系人员</label>
                                    <input type="text" class="form-control" id="id_person"  name="person" value="{{ person|default:"" }}" placeholder="联系人员">
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="id_begin_time">签约时间</label>
                                    <input type="text" class="form-control" id="id_begin_time" name="begin_time" value="{{ begin_time|default:"" }}" placeholder="签约开始时间">
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="id_end_time">止</label>
                                    <input type="text" class="form-control" id="id_end_time" name="end_time" value="{{ end_time|default:"" }}" placeholder="签约截止时间">
                                </div>
                                <button type="submit" class="btn btn-success"><i class="fa fa-search"></i> 查询</button>
                                <button type="button" id="btn_reset" class="btn btn-success"><i class="fa fa-undo"></i> 重置</button>
                            </form>
                        </div>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>企业名称/姓名</th>
                                <th>类型</th>
                                <th>联系人</th>
                                <th>签约时间</th>
                                <th>联系电话</th>
                                <th>签约内容</th>
                                <th>顾问律师</th>
                                {% if request|has_permission:"advisor:consult-unit-update" or  request|has_permission:"advisor:consult-unit-delete"%}
                                    <th>选项</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for c in consultants %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ c.unit_name }}</td>
                                    <td>{{ c.get_unit_type_display }}</td>
                                    <td>{{ c.person }}</td>
                                    <td>{{ c.sign_begin }}--{{ c.sign_end }}</td>
                                    <td>{{ c.telephone }}</td>
                                    <td>{{ c.get_scheme_display }}</td>
                                    <td>{{ c.get_lawyer_list }}</td>
                                    <td>
                                        {% if request|has_permission:"advisor:consult-unit-update" %}
                                            <a class="btn btn-xs btn-primary " href="{% url 'advisor:consult-unit-update' c.id %}">修改</a>
                                        {% endif %}
                                        {% if request|has_permission:"advisor:consult-unit-delete" %}
                                            <a class="btn  btn-xs btn-danger btn-del" href="#" data-item="{% url 'advisor:consult-unit-delete' c.id %}">删除</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extjs %}
    <script>
    $(function () {
        $("#id_begin_time, #id_end_time").datepicker({
            format: "yyyy-mm-dd",
            language: "zh-CN",
            autoclose: true,
        });
        $("#btn_reset").click(function () {
            $("#id_unit_name").val("");
            $("#id_person").val("");
            $("#id_begin_time").val("");
            $("#id_end_time").val("");
        });
    })

    </script>
{% endblock %}

advisor/templates/advisor/unit_dispach_list.html
{% extends 'rbac/base.html' %}{% load static rbac %}
{% block title %}分配顾问单位{% endblock title %}
{% block css %}
    <style>
        {#.table tr > td {#}
        {#    border-top: 0px!important;#}
        {#    vertical-align: middle!important;#}
        {#}#}
        {#.btn-user{#}
        {#    width:70px!important;#}
        {#}#}
    </style>
{% endblock %}
{% block right %}
    <div class="row">
        <h3 class="text-center">分配顾问单位</h3>
    </div>
    <div class="row">
        <div class="col-md-offset-3 col-md-3 col-sm-6 col-xs-12">
            <div class="panel panel-default mgt">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">企业法律顾问</h3>
                </div>
                <div class="panel-body" style="min-height: 500px;">
                    <table class="table table-responsive table-striped">
                        {% for unit in units %}
                            <tr>
                                <td>{{ unit.unit_name }}</td>
                                <td>
                                    <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal"
                                            data-uri="{% url 'advisor:consult-unit-update' unit.id %}">分配
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="panel panel-default mgt">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">个人法律顾问</h3>
                </div>
                <div class="panel-body" style="min-height: 500px;">
                    <table class="table table-responsive table-striped">
                        {% for person in persons %}
                            <tr>
                                <td>{{ person.unit_name }}</td>
                                <td>
                                    <button class="btn btn-primary btn-sm" data-toggle="modal"
                                            data-target="#myModal"
                                            data-uri="{% url 'advisor:consult-unit-update' person.id %}">分配
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="myModal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">分配顾问单位</h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" data-dismiss="modal" id="sava-edit-btn">确定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
{% endblock right %}

{% block extjs %}
<script>
    $(function () {
        {% if form.success %}
            Swal.fire(
              '用户创建成功',
              '',
              'success'
            )
        {% endif %}
    $("#sava-edit-btn").click(function () {
        var is_assign = $("#id_is_assign").val();
        if(is_assign.length==0){
            alert("请设置分配确认");
            return false;
        }

        $("#id_form").submit();
    })
        $('#myModal').on('show.bs.modal', function(event){
            var button = $(event.relatedTarget);
            var uri = button.attr('data-uri');

            $(this).find('.modal-body').load( uri+ '?_format=html', function(response, status, xhr){
              if (status == "error") {
                var msg = "Sorry but there was an error: ";
                modal.find('.modal-body').html(msg + xhr.status + " " + (typeof xhr === 'string' ? xhr : xhr.responseText || xhr.statusText || 'Unknown error!'));
              }
            });
        })
    })
</script>
{% endblock %}