adm/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from adm.views import (
    UserAuthView,
    UserCategoryListView,
    OfficeView,
    OfficeUpdateView,
    UserDetailChangeView,
    UserDetailView,
    MyCase,
    CaseCategory,
    CaseInfo,
    CaseDistributeView,
    CaseDoingListView,
    CaseSearchListView)

urlpatterns = [
    url(r'^user_auth/$', UserAuthView.as_view(), name="user-auth"),
    url(r'^user_category_list/$', UserCategoryListView.as_view(), name="user-category-list"),
    url(r'^user_detail_change/$', UserDetailChangeView.as_view(), name="user-detail-change"),
    url(r'^user_detail/(?P<pk>\d+)/$', UserDetailView.as_view(), name="user-detail"),
    url(r'^office/$', OfficeView.as_view(), name="office"),
    url(r'^office_update/(?P<pk>\d+)/$', OfficeUpdateView.as_view(), name="office-update"),

    url(r'^my_case/$', MyCase.as_view(), name="my-case"),
    url(r'^case_category/$', CaseCategory.as_view(), name="case-category"),

    url(r'^case_info/$', CaseInfo.as_view(), name="case-info"),
    url(r'^case_distrib_list/$', CaseDistributeView.as_view(), name="case-distrib-list"),
    url(r'^case_doing_list/$', CaseDoingListView.as_view(), name="case-doing-list"),
    url(r'^case_search_list/$', CaseSearchListView.as_view(), name="case-search-list"),

]

calculator/api/urls.py
#-*-coding:utf-8-*-
from django.conf.urls import url

from calculator.api.views import AreaCodeListAPIView, IndusAverWageAPIView, IndusNurseWageAPIView, FuneralExpenseAPIView

__author__ = 'malixin'


urlpatterns = [
    url(r'^area_code_list/$', AreaCodeListAPIView.as_view(), name='area-code-list'),
    url(r'^indust_aver_wage/$', IndusAverWageAPIView.as_view(), name='indust-aver-wage'),
    url(r'^indust_nurse_wage/$', IndusNurseWageAPIView.as_view(), name='indust-nurse-wage'),
    url(r'^funeral/$', FuneralExpenseAPIView.as_view(), name="calc-funeral-expense"),
]

calculator/urls.py
from django.conf.urls import url, include

from calculator.views import TrafficCalcView, CalculatorView, HospitalCalcView, AppraiseCalcView, RelationCalcView, \
    CalculatorResultView

urlpatterns = [
    url(r'^$', CalculatorView.as_view(), name="calc-index"),
    url(r'^traffic/$', TrafficCalcView.as_view(), name="traffic-index"),
    url(r'^hospital/$', HospitalCalcView.as_view(), name="hospital-index"),
    url(r'^appraise/$', AppraiseCalcView.as_view(), name="appraise-index"),
    url(r'^relation/$', RelationCalcView.as_view(), name="relation-index"),
    url(r'^result/$', CalculatorResultView.as_view(), name="calc-result"),

]

lawyer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.authtoken import views

from rbac.account import login, logout, password_change

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^password/change/(?P<pk>\d+)/$', password_change, name='password-change'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^api-token-auth/', views.obtain_auth_token, name="obtain-auth-token"),
    url(r'^rbac/', include('rbac.urls', namespace='rbac')),
    url(r'^adm/', include('adm.urls', namespace='adm')),
    url(r'^adm/api/', include('adm.api.urls')),
    url(r'^advisor/', include('advisor.urls', namespace='advisor')),
    url(r'^calculator/', include('calculator.urls', namespace='calculator')),
    url(r'^calculator/api/', include('calculator.api.urls', namespace='calculator-api')),
    url(r'^calc_manager/', include('calculator.calculator_urls', namespace='calc-mgr')),
    url(r'^civil/', include('civilcase.urls', namespace='civil-case')),
    url(r'^criminal/', include('crimicase.urls', namespace='criminal')),
    url(r'^admincase/', include('admincase.urls', namespace='admincase')),
    url(r'^private/', include('crimiprivate.urls', namespace='private')),
    url(r'^crmcivil/', include('crimicivil.urls', namespace='crmcivil')),
    url(r'^print/', include('civilcase.print_urls', namespace='print')),
    url(r'^civil/api/', include('civilcase.api.urls', namespace='civil-api')),
]

advisor/models.py
from django.db import models

from baseinfo.constants import IS_ASSIGN
from rbac.models import UserInfo


class ConsultantUnit(models.Model):
    """顾问单位"""
    SCHEME = (
        (1, '方案A'),
        (2, '方案B'),
        (3, '方案C'),
        (4, '方案D'),
    )
    TYPE = (
        (0, '企业'),
        (1, '个人'),
    )
    unit_name = models.CharField(verbose_name="企业名称/姓名", max_length=120)
    unit_type = models.IntegerField(verbose_name="类型", choices=TYPE, default=0)
    person = models.CharField(verbose_name="联系人员", max_length=64, blank=True, default="")
    sign_begin = models.DateField(verbose_name="签约开始时间")
    sign_end = models.DateField(verbose_name="截止时间")
    telephone = models.CharField(verbose_name="联系电话", max_length=32)
    scheme = models.IntegerField(verbose_name="签约方案", choices=SCHEME)
    address = models.CharField(verbose_name="地址", max_length=120)
    lawyer = models.ManyToManyField(verbose_name="律师姓名", to=UserInfo, blank=True)
    is_assign = models.IntegerField(verbose_name="分配确认", choices=IS_ASSIGN, blank=True, null=True)
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    def __str__(self):
        return self.unit_name

    class Meta:
        verbose_name = "顾问单位"
        verbose_name_plural = verbose_name

    def get_lawyer_list(self):
        lawyer_list = []
        for user in self.lawyer.all():
            lawyer_list.append(user.real_name)
        print(lawyer_list)
        return ",".join(lawyer_list)

calculator/models.py
# coding=utf-8
from django.db import models

from calculator.constants import SUPPORTED_TYPE, RELATION_TYPE


class AreaCode(models.Model):
    """
    地区编码
    """
    code = models.CharField(verbose_name='地区编码', primary_key=True, max_length=18)
    name = models.CharField(verbose_name='地区名称', max_length=50)

    class Meta:
        verbose_name = '地区编码表'
        verbose_name_plural = verbose_name
        ordering = ['code']

    def __str__(self):
        return self.name


class IncomeExpendItem(models.Model):
    """居民人均收支项"""
    name = models.CharField(verbose_name="项目名称", max_length=128)

    class Meta:
        verbose_name = '居民人均收支项'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Industry(models.Model):
    """行业管理"""
    name = models.CharField(verbose_name="行业名称", max_length=128)
    standard = models.IntegerField(verbose_name="护理标准", choices=((0, '否'), (1, '是')), default=0)

    class Meta:
        verbose_name = '行业管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{}({})".format(self.name, self.id)


class IndusAverWage(models.Model):
    """行业城镇单位在岗职工平均工资"""
    province = models.ForeignKey(AreaCode, verbose_name="省份", on_delete=models.CASCADE)
    industry = models.ForeignKey(Industry, verbose_name="行业名称", on_delete=models.CASCADE)
    years = models.IntegerField(verbose_name="年份", )
    aver_wage = models.DecimalField(verbose_name="平均工资", max_digits=10, decimal_places=2, default=0)
    day_aver_wage = models.DecimalField(verbose_name="平均日工资", max_digits=10, decimal_places=2, default=0)

    class Meta:
        verbose_name = '行业平均工资'
        verbose_name_plural = verbose_name
        ordering = ["-years", "province", "industry"]

    def __str__(self):
        return "{}{}".format(self.province.name, self.industry.name)


class ResIncomeExpend(models.Model):
    """居民人均收支情况表"""
    province = models.ForeignKey(AreaCode, verbose_name="省份", on_delete=models.CASCADE)
    inc_exp_item = models.ForeignKey(IncomeExpendItem, verbose_name="收支项", on_delete=models.CASCADE)
    years = models.IntegerField(verbose_name="年份", )
    total_money = models.DecimalField(verbose_name="总金额", max_digits=10, decimal_places=2, default=0)

    class Meta:
        verbose_name = '居民人均收支情况表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{}{}".format(self.province.name, self.inc_exp_item.name)


class CalculatorUser(models.Model):
    """计算人员"""
    name = models.CharField(verbose_name="计算人员", max_length=32, default="anyone")

    class Meta:
        verbose_name = '计算人员'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SupportedPerson(models.Model):
    """被抚养人"""
    CHOICES = (
              ('', '----'),
              (1, '有'),
              (0, '无'),
              )
    user = models.ForeignKey(CalculatorUser, verbose_name="当事人", on_delete=models.CASCADE)
    relation_type = models.IntegerField(verbose_name="与当事人关系", choices=SUPPORTED_TYPE)
    action_ability = models.IntegerField(verbose_name="是否有残障", choices=CHOICES, default=0)
    is_income = models.IntegerField(verbose_name="是否有收入", choices=CHOICES, default=0)
    relation_age = models.IntegerField(verbose_name="年龄")

    class Meta:
        verbose_name = '被抚养人'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.get_relation_type_display()


class RelationPerson(models.Model):
    """直系亲属"""
    CHOICES = (
          ('', '----'),
          (1, '有'),
          (0, '无'),
    )
    user = models.ForeignKey(CalculatorUser, verbose_name="当事人", on_delete=models.CASCADE)
    relation_type = models.IntegerField(verbose_name="与当事人关系", choices=RELATION_TYPE)
    action_ability = models.IntegerField(verbose_name="是否有残障", choices=CHOICES, default=0)
    is_income = models.IntegerField(verbose_name="是否有收入", choices=CHOICES, default=0)
    relation_age = models.IntegerField(verbose_name="年龄")

    class Meta:
        verbose_name = '被抚养人'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.get_relation_type_display()

calculator/api/views.py
# -*-coding:utf-8-*-
import datetime

from calculator.api.serializers import AreaCodeSerializer, IndusAverWageSerializer
from lawyer import settings

__author__ = 'malixin'


from django.db.models import Q

from rest_framework.generics import ListAPIView
from rest_framework.permissions import AllowAny, IsAuthenticatedOrReadOnly, IsAuthenticated
from rest_framework.response import Response

from rest_framework.views import APIView
from calculator.models import AreaCode, IndusAverWage, ResIncomeExpend


class AreaCodeListAPIView(ListAPIView):
    """
    地区编码
    """
    permission_classes = [AllowAny]
    queryset = AreaCode.objects.all()
    serializer_class = AreaCodeSerializer
    pagination_class = None

    def get_queryset(self):
        code = self.request.GET.get("code", None)
        if code and len(code) == 2:
            return AreaCode.objects.extra(where=['left(code,2)=%s', 'length(code)=4'], params=[code])
        elif code and len(code) == 4:
            return AreaCode.objects.extra(where=['left(code,4)=%s', 'length(code)=6'], params=[code])
        else:
            return AreaCode.objects.extra(where=['length(code)=2'])


class IndusAverWageAPIView(APIView):
    """
    行业工资标准
    """
    def get(self, request, *args, **kwargs):
        indust_id = request.GET.get("indust_id", None)
        province = request.GET.get("province", None)
        court_province = request.GET.get("court_province", None)

        indust_wage = IndusAverWage.objects.filter(industry_id=int(indust_id), province_id=province).order_by("-years").first()
        court_indust_wage = IndusAverWage.objects.filter(industry_id=int(indust_id), province_id=court_province).order_by("-years").first()

        result = {
            "success": "false",
        }
        if indust_wage and court_indust_wage:
            if indust_wage.day_aver_wage < court_indust_wage.day_aver_wage:
                indust_wage = court_indust_wage

            serializer = IndusAverWageSerializer(indust_wage)
            result["success"] = "true"
            result["result"] = serializer.data
            return Response(result)
        else:
            result["error_msg"] = "无法获取行业工资标准"
            return Response(result)


class IndusNurseWageAPIView(APIView):
    """
    行业护理日工资标准
    """
    def get(self, request, *args, **kwargs):
        calculator = request.session.get(settings.CALCULATOR_SESSION_KEY)
        province = calculator.get("province", None)
        court_province = calculator.get("court_province", None)

        indust_wage = IndusAverWage.objects.filter(province_id=province, industry__standard=1).order_by("-years").first()
        court_indust_wage = IndusAverWage.objects.filter(province_id=court_province, industry__standard=1).order_by("-years").first()

        result = {
            "success": "false",
        }
        if indust_wage and court_indust_wage:
            serializer = IndusAverWageSerializer(indust_wage)
            result["success"] = "true"
            result["result"] = serializer.data
            return Response(result)
        else:
            result["error_msg"] = "无法获取护理工资标准"
            return Response(result)


class FuneralExpenseAPIView(APIView):
    """丧葬费"""
    def get(self, request, *args, **kwargs):
        dead = request.GET.get("dead", None)
        province = request.GET.get("province", None)
        court_province = request.GET.get("court_province", None)

        result = {
            "success": "false",
        }
        if dead == "1":
            # 丧葬费 id = 6 (丧葬费)
            last_year = datetime.datetime.now().year - 1
            res_inc_exp = ResIncomeExpend.objects.filter(inc_exp_item_id=6, province_id=province, years=last_year).first()
            court_res_inc_exp = ResIncomeExpend.objects.filter(inc_exp_item_id=6, province_id=court_province, years=last_year).first()

            if res_inc_exp and court_res_inc_exp:
                if res_inc_exp.total_money >= court_res_inc_exp.total_money:
                    result["success"] = "true"
                    result["funeral_expense"] = res_inc_exp.total_money
                else:
                    result["success"] = "true"
                    result["funeral_expense"] = court_res_inc_exp.total_money
            else:
                result["funeral_expense"] = 0

        return Response(result)

calculator/templates/calculator/calculator_panel.html
{% extends 'rbac/base.html' %}{% load static rbac %}
{% block title %}计算器维护{% endblock title %}
{% block right %}
    {% for item in children_menus %}
        {% if item.is_menu %}
        <div class="ynbox">
            <div class="ynntowbox">
                <a href="{{ item.url }}">
                    {% if item.icon %}
                        <img src="{% static item.icon %}">
                    {% else %}
                        <img src="{% static 'lawyer/img/fpgwdw.jpg' %}">
                    {% endif %}
                </a>
            </div>
            <div class="ynname"><a href="{{ item.url }}">{{ item.title }}</a></div>
        </div>
        {% endif %}
    {% endfor %}

{% endblock right %}

calculator/templates/calculator/income_expend_item_list.html
{% extends 'rbac/base.html' %}{% load static rbac%}
{% block title %} 居民人均收支项 {% endblock title %}
{% block css %}
    <style>
        .mgt{
           margin-top: 20px;
        }
        .panel-heading{
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            overflow: hidden;
        }
    </style>
{% endblock %}
{% block right %}
    <div class="row">
        <div class="container-fluid mgt">
            <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-ex">
                            <div class="row">
                                <div class="col-md-4 col-xs-4"><span class="panel-title h34">居民人均收支项</span></div>
                                <div class="col-md-8 col-xs-8">
                                <span class="right">
                                    {% if request|has_permission:'calc-mgr:income-expend-item-add' %}
                                        <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#myModal" data-uri="{% url 'calc-mgr:income-expend-item-add' %}">
                                            <i class="glyphicon glyphicon-plus">增加</i>
                                        </button>
                                    {% endif %}
                                </span>
                                </div>
                            </div>
                        </div>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th class="text-center">ID</th>
                                <th>项目名称</th>
                                {% if request|has_permission:"calc-mgr:income-expend-item-update" or  request|has_permission:"advisor:consult-unit-delete"%}
                                    <th>选项</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for c in inc_exp_items %}
                                <tr>
                                    <td class="text-center">{{ c.id }}</td>
                                    <td>{{ c.name }}</td>
                                    <td>
                                        {% if request|has_permission:"calc-mgr:income-expend-item-update" %}
                                         <button class="btn btn-xs btn-primary" data-toggle="modal" data-target="#myModal" data-uri="{% url 'calc-mgr:income-expend-item-update' c.id %}">
                                            修改
                                        </button>
                                        {% endif %}
                                        {% if request|has_permission:"calc-mgr:income-expend-item-del" %}
                                            <a class="btn  btn-xs btn-danger btn-del" href="#" data-item="{% url 'calc-mgr:income-expend-item-del' c.id %}">删除</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
            </div>
        </div>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="myModal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">居民人均收支项</h4>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" id="save-edit-btn">保存</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extjs %}
    <script>
    $(function () {
        $("#id_begin_time, #id_end_time").datepicker({
            format: "yyyy-mm-dd",
            language: "zh-CN",
            autoclose: true,
        });
        $("#btn_reset").click(function () {
            $("#id_unit_name").val("");
            $("#id_person").val("");
            $("#id_begin_time").val("");
            $("#id_end_time").val("");
        });

        $("#save-edit-btn").click(function () {
            $("#id_form").submit();
        })
        $('#myModal').on('show.bs.modal', function(event){
            var button = $(event.relatedTarget);
            var uri = button.attr('data-uri');
            console.log(uri);
            $(this).find('.modal-body').load( uri, function(response, status, xhr){
              if (status == "error") {
                var msg = "Sorry but there was an error: ";
                modal.find('.modal-body').html(msg + xhr.status + " " + (typeof xhr === 'string' ? xhr : xhr.responseText || xhr.statusText || 'Unknown error!'));
              }
            });
        })
    })

    </script>
{% endblock %}

calculator/templates/calculator/index.html
{% extends 'mlawyer/mbase.html' %}{% load static%}
{% block title %}计算器{% endblock title %}
{% block content %}
    <div class="col-xs-4 col-sm-4">
        <div class="xj">
            <a href="{% url 'calculator:traffic-index' %}"><img src="{% static 'mobile/img/jtsg.png' %}" alt=""/></a>
        </div>
    </div>
{% endblock content %}

calculator/templates/calculator/industry_list.html
{% extends 'rbac/base.html' %}{% load static rbac%}
{% block title %} 行业管理列表 {% endblock title %}
{% block css %}
    <style>
        .mgt{
           margin-top: 20px;
        }
        .panel-heading{
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            overflow: hidden;
        }
    </style>
{% endblock %}
{% block right %}
    <div class="row">
        <div class="container-fluid mgt">
            <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-ex">
                            <div class="row">
                                <div class="col-md-4 col-xs-4"><span class="panel-title h34">行业管理列表</span></div>
                                <div class="col-md-8 col-xs-8">
                                <span class="right">
                                    {% if request|has_permission:'calc-mgr:industry-add' %}
                                        <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#myModal" data-uri="{% url 'calc-mgr:industry-add' %}">
                                            <i class="glyphicon glyphicon-plus">增加</i>
                                        </button>
                                    {% endif %}
                                </span>
                                </div>
                            </div>
                        </div>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th class="text-center">ID</th>
                                <th>行业名称</th>
                                <th>护理标准</th>
                                {% if request|has_permission:"calc-mgr:industry-update" or  request|has_permission:"calc-mgr:industry-del"%}
                                    <th>选项</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for ind in industries %}
                                <tr>
                                    <td class="text-center">{{ ind.id }}</td>
                                    <td>{{ ind.name }}</td>
                                    <td>{{ ind.get_standard_display }}</td>
                                    <td>
                                        {% if request|has_permission:"calc-mgr:industry-update" %}
                                         <button class="btn btn-xs btn-primary" data-toggle="modal" data-target="#myModal" data-uri="{% url 'calc-mgr:industry-update' ind.id %}">
                                            修改
                                        </button>
                                        {% endif %}
                                        {% if request|has_permission:"calc-mgr:industry-del" %}
                                            <a class="btn  btn-xs btn-danger btn-del" href="#" data-item="{% url 'calc-mgr:industry-del' ind.id %}">删除</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="myModal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">行业管理</h4>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" id="save-edit-btn">保存</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extjs %}
    <script>
    $(function () {
        $("#id_begin_time, #id_end_time").datepicker({
            format: "yyyy-mm-dd",
            language: "zh-CN",
            autoclose: true,
        });
        $("#btn_reset").click(function () {
            $("#id_unit_name").val("");
            $("#id_person").val("");
            $("#id_begin_time").val("");
            $("#id_end_time").val("");
        });

        $("#save-edit-btn").click(function () {
            $("#id_form").submit();
        })
        $('#myModal').on('show.bs.modal', function(event){
            var button = $(event.relatedTarget);
            var uri = button.attr('data-uri');
            console.log(uri);
            $(this).find('.modal-body').load( uri, function(response, status, xhr){
              if (status == "error") {
                var msg = "Sorry but there was an error: ";
                modal.find('.modal-body').html(msg + xhr.status + " " + (typeof xhr === 'string' ? xhr : xhr.responseText || xhr.statusText || 'Unknown error!'));
              }
            });
        })
    })

    </script>
{% endblock %}

calculator/templates/calculator/relationship_1.html
{% extends 'mlawyer/mbase.html' %}{% load static %}
{% block title %}被抚(扶)养人及直系亲属信息{% endblock title %}
{% block css %}
    <style>
        .mgt-20 {
            margin-top: 20px;
        }
    </style>
{% endblock %}
{% block header %}{% endblock %}
{% block content %}
    <div class="mgt-20"></div>
    <form action="" method="post">
        {% csrf_token %}
    <div class="panel panel-default" id="id_{{ relation_formset.prefix }}">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-10">
                    <h3 class="panel-title">被抚(扶)养人及直系亲属信息</h3>
                </div>
                <div class="col-xs-2 text-right formset-add-btn">
                </div>
            </div>
        </div>
        <table class="table table-responsive  table-bordered" >
            <thead>
            <th class="text-center" style="width:30%;font-size: 12px;">与当事人关系</th>
            <th class="text-center" style="width:20%;font-size: 12px;">行为能力</th>
            <th class="text-center" style="font-size: 12px;">劳动收入</th>
            <th class="text-center" style="width:20%;font-size:12px;">年龄</th>
            </thead>
            <tbody class="formset-body">
            {{ relation_formset.management_form }}
            {% for relation in relation_formset %}
                <tr>
                    <td class="text-center">
                        {{ relation.relation_type }}
                    </td>
                    <td class="text-center">
                        {{ relation.action_ability }}
                    </td>
                </tr>
                <tr>
                    <td class="text-center">
                        {{ relation.is_income }}
                    </td>
                    <td class="text-center">
                        <div class="input-group">
                            {{ relation.relation_age }}
                            <div class="input-group-btn">
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    <div class="panel-footer">
        <div class="row">
            <div class="col-xs-12 text-center">
                <button type="submit" class="btn btn-success">计算</button>
            </div>
        </div>
    </div>
    </div>
    </form>
{% endblock content %}
{% block extjs %}
    <script type="text/javascript" src="{% static 'lawyer/js/jquery.formset.js' %}"></script>
    <script>
        $(function () {
             $('#id_{{relation_formset.prefix }} tbody tr').formset({
                'prefix': '{{ relation_formset.prefix }}',
                'addCssClass': 'add-row btn btn-success btn-xs',
                'deleteCssClass': 'delete-row btn btn-danger',
                'deleteText': '<i class="fa fa-remove"></i>',
                'addText': '<i class="fa fa-plus"></i>',
                added: function (row) {
                    var xh = $("#id_{{ relation_formset.prefix }}-TOTAL_FORMS").val();
                    row.find(".input-group-addon").text(xh);
                }
            });
        })
    </script>
{% endblock %}