adm/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from adm.views import (
    UserAuthView,
    UserCategoryListView,
    OfficeView,
    OfficeUpdateView,
    UserDetailChangeView,
    UserDetailView,
    MyCase,
    CaseCategory,
    CaseInfo,
    CaseDistributeView,
    CaseDoingListView,
    CaseSearchListView)

urlpatterns = [
    url(r'^user_auth/$', UserAuthView.as_view(), name="user-auth"),
    url(r'^user_category_list/$', UserCategoryListView.as_view(), name="user-category-list"),
    url(r'^user_detail_change/$', UserDetailChangeView.as_view(), name="user-detail-change"),
    url(r'^user_detail/(?P<pk>\d+)/$', UserDetailView.as_view(), name="user-detail"),
    url(r'^office/$', OfficeView.as_view(), name="office"),
    url(r'^office_update/(?P<pk>\d+)/$', OfficeUpdateView.as_view(), name="office-update"),

    url(r'^my_case/$', MyCase.as_view(), name="my-case"),
    url(r'^case_category/$', CaseCategory.as_view(), name="case-category"),

    url(r'^case_info/$', CaseInfo.as_view(), name="case-info"),
    url(r'^case_distrib_list/$', CaseDistributeView.as_view(), name="case-distrib-list"),
    url(r'^case_doing_list/$', CaseDoingListView.as_view(), name="case-doing-list"),
    url(r'^case_search_list/$', CaseSearchListView.as_view(), name="case-search-list"),

]

lawyer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.authtoken import views

from rbac.account import login, logout, password_change

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^password/change/(?P<pk>\d+)/$', password_change, name='password-change'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^api-token-auth/', views.obtain_auth_token, name="obtain-auth-token"),
    url(r'^rbac/', include('rbac.urls', namespace='rbac')),
    url(r'^adm/', include('adm.urls', namespace='adm')),
    url(r'^adm/api/', include('adm.api.urls')),
    url(r'^advisor/', include('advisor.urls', namespace='advisor')),
    url(r'^calculator/', include('calculator.urls', namespace='calculator')),
    url(r'^calculator/api/', include('calculator.api.urls', namespace='calculator-api')),
    url(r'^calc_manager/', include('calculator.calculator_urls', namespace='calc-mgr')),
    url(r'^civil/', include('civilcase.urls', namespace='civil-case')),
    url(r'^criminal/', include('crimicase.urls', namespace='criminal')),
    url(r'^admincase/', include('admincase.urls', namespace='admincase')),
    url(r'^private/', include('crimiprivate.urls', namespace='private')),
    url(r'^crmcivil/', include('crimicivil.urls', namespace='crmcivil')),
    url(r'^print/', include('civilcase.print_urls', namespace='print')),
    url(r'^civil/api/', include('civilcase.api.urls', namespace='civil-api')),
]

rbac/urls.py
from django.conf.urls import url, include

from rbac.account import user_list, user_add, user_edit, user_del
from .views import permission_list, permission_add, permission_edit, permission_del, role_list, role_edit, role_del, \
    permission_auth, permission_batch

urlpatterns = [
    url(r'^permission_list/$', permission_list, name="permission-list"),
    url(r'^permission/add/$', permission_add, name='permission-add'),
    url(r'^permission/edit/(?P<pk>\d+)/$', permission_edit, name='permission-edit'),
    url(r'^permission/del/(?P<pk>\d+)/$', permission_del, name='permission-del'),
    url(r'^permission/auth/$', permission_auth, name='permission-auth'),
    url(r'^permission/batch/$', permission_batch, name='permission-batch'),

    url(r'^role/list/$', role_list, name='role-list'),
    url(r'^role/edit/(?P<pk>\d+)/$', role_edit, name='role-edit'),
    url(r'^role/del/(?P<pk>\d+)/$', role_del, name='role-del'),

    url(r'^user/list/$', user_list, name='user-list'),
    url(r'^user/add/$', user_add, name='user-add'),
    url(r'^user/edit/(?P<pk>\d+)/$', user_edit, name='user-edit'),
    url(r'^user/del/(?P<pk>\d+)/$', user_del, name='user-del'),

]

rbac/models.py
import datetime

from django.db import models
from django.utils import timezone
from enum import Enum, unique


# class Post(Enum):
#     """律师类型"""
#     Major = 1
#     Part = 2
#     Practs = 3
#     Manager = 4
#     Administrative = 5
#     Partner = 6
#     Student = 7
#
#
# POST = (
#     (Post.Major.value, '专职律师'),
#     (Post.Part.value, '兼职律师'),
#     (Post.Practs.value, '实习律师'),
#     (Post.Manager.value, '客户经理'),
#     (Post.Administrative.value, '行政人员'),
#     (Post.Partner.value, '律所合伙人'),
#     (Post.Student.value, '学员'),
# )
from baseinfo.models import Post


class Menu(models.Model):
    """
    菜单
    """
    title = models.CharField(verbose_name='菜单', max_length=32)
    icon = models.CharField(verbose_name='图标', max_length=32)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '菜单'
        verbose_name_plural = verbose_name


class Permission(models.Model):
    """
    权限表
    """
    title = models.CharField(verbose_name='标题', max_length=64)
    url = models.CharField(verbose_name='链接地址', max_length=128, unique=True)
    name = models.CharField(verbose_name='别名', max_length=64, unique=True, null=False, blank=False)
    pid = models.ForeignKey(verbose_name='父级权限', to='Permission', related_name='ps', null=True, blank=True,
                            limit_choices_to={'pid__isnull': True}, on_delete=models.SET_NULL)
    is_menu = models.BooleanField(verbose_name='菜单', default=False)
    icon = models.CharField(verbose_name='图标', max_length=64, blank=True, null=True)
    sort = models.IntegerField(verbose_name='排序', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '权限信息'
        verbose_name_plural = verbose_name


class Role(models.Model):
    """
    角色
    """
    name = models.CharField(verbose_name='角色名称', max_length=32)
    permissions = models.ManyToManyField(verbose_name='拥有的所有权限', to='Permission', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '角色管理'
        verbose_name_plural = verbose_name


class UserInfo(models.Model):
    """
    用户表
    """
    name = models.CharField(verbose_name='登录名', max_length=32, unique=True)
    real_name = models.CharField(verbose_name='姓名', max_length=32)
    gender = models.IntegerField(verbose_name="性别", choices=((1, "男"), (2, "女")), blank=True, null=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    telephone = models.CharField(verbose_name='手机', max_length=16)
    email = models.CharField(verbose_name='邮箱', max_length=32, blank=True, null=True)
    post = models.ForeignKey(Post, verbose_name="用户类型", on_delete=models.SET_NULL, null=True)
    job = models.CharField(verbose_name="职务", max_length=64, blank=True, null=True)
    # years = models.CharField(verbose_name="执业年限", max_length=24, blank=True, null=True)
    job_time = models.DateField(verbose_name="执业时间", blank=True, null=True)
    license_num = models.CharField(verbose_name="律师证号", max_length=32, blank=True, null=True)
    prof_title = models.CharField(verbose_name="律师职称", max_length=64, blank=True, null=True)
    is_superuser = models.BooleanField(verbose_name='超级管理员', default=False)
    is_active = models.BooleanField(verbose_name='是否有效', default=True)
    date_joined = models.DateTimeField(verbose_name='创建时间', default=timezone.now)
    last_login = models.DateTimeField(verbose_name='最近登录时间', blank=True, null=True)
    is_update = models.BooleanField(verbose_name="是否完善", default=False)
    roles = models.ManyToManyField(verbose_name='所属角色', to='Role', blank=True)

    def __str__(self):
        return self.real_name if self.real_name else self.name

    class Meta:
        verbose_name = '用户管理'
        verbose_name_plural = verbose_name

    def practice_years(self):
        if self.job_time:
            return datetime.datetime.now().year - self.job_time.year
        else:
            return 0

rbac/views.py
from collections import OrderedDict

from django.forms import formset_factory
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from lawyer import settings
from rbac.forms import PermissionForm, RoleForm, MultiPermissionForm
from rbac.models import Permission, Role, UserInfo
from rbac.utils import get_all_url_dict


def permission_list(request):
    """
    权限信息
    :param request:
    :return:
    """

    root_permission_list = []

    permissions = Permission.objects.filter(pid__isnull=True).order_by('sort')

    root_permission_queryset = permissions.values('id', 'title', 'url', 'name', 'sort', 'is_menu')
    root_permission_dict = {}
    for item in root_permission_queryset:
        item['children'] = []
        root_permission_list.append(item)
        root_permission_dict[item['id']] = item

    node_permission_list = Permission.objects.filter(pid__in=permissions).order_by('sort').values('id', 'title', 'url', 'name', 'sort', 'is_menu', 'pid', 'pid__title')
    for node in node_permission_list:
        pid = node['pid']
        root_permission_dict[pid]['children'].append(node)
    # print(root_permission_list)
    context = {
        'permissions': root_permission_list,
    }
    return render(request, template_name='rbac/permission_list.html', context=context)


def permission_add(request):
    """
    添加权限
    :param request:
    :return:
    """
    if request.method == 'GET':
        form = PermissionForm()
    else:
        form = PermissionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('rbac:permission-list'))
    return render(request, 'rbac/permission_change.html', {'form': form})


def permission_edit(request, pk):
    """
    编辑权限
    :param request:
    :return:
    """
    obj = Permission.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('权限不存在')

    if request.method == 'GET':
        form = PermissionForm(instance=obj)
    else:
        form = PermissionForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('rbac:permission-list'))
    return render(request, 'rbac/permission_change.html', {'form': form})


def permission_del(request, pk):
    """
    删除权限
    :param request:
    :return:
    """
    Permission.objects.filter(id=pk).delete()
    return redirect(request.META['HTTP_REFERER'])


def permission_batch(request):
    """
    批量操作权限
    :param request:
    """
    post_type = request.GET.get('type')

    MultiPermissionFormSet = formset_factory(MultiPermissionForm, extra=0)
    add_formset = None
    update_formset = None

    if request.method == 'POST' and post_type == 'add':
        formset = MultiPermissionFormSet(request.POST)
        if not formset.is_valid():
            add_formset = formset
        else:
            for row_dict in formset.cleaned_data:
                row_dict.pop('id')
                url = row_dict.pop("url")
                Permission.objects.update_or_create(defaults=row_dict, url=url)

    if request.method == 'POST' and post_type == 'update':
        formset = MultiPermissionFormSet(request.POST)
        if formset.is_valid():
            for row_dict in formset.cleaned_data:
                permission_id = row_dict.pop('id')
                Permission.objects.filter(id=permission_id).update(**row_dict)
        else:
            update_formset = formset

    permissions = Permission.objects.order_by('sort').values('id', 'title', 'url', 'name', 'pid_id', 'is_menu', 'icon', 'sort')
    permisssion_dict = OrderedDict()
    for per in permissions:
        permisssion_dict[per['name']] = per
    permission_name_set = set(permisssion_dict.keys())

    router_dict = get_all_url_dict(ignore_namespace_list=settings.IGNORE_NAMESPACE_LIST)
    for row in permissions:
        name = row['name']
        if name in router_dict:
            router_dict[name].update(row)
    router_name_set = set(router_dict.keys())

    # 需要新建：数据库无、路由有
    if not add_formset:
        add_name_list = router_name_set - permission_name_set
        add_formset = MultiPermissionFormSet(
            initial=[row for name, row in router_dict.items() if name in add_name_list])

    # 需要删除：数据库有、路由无
    destroy_name_list = permission_name_set - router_name_set
    destroy_formset = MultiPermissionFormSet(
        initial=[row for name, row in permisssion_dict.items() if name in destroy_name_list])

    # 需要更新：数据库有、路由有
    if not update_formset:
        update_name_list = permission_name_set.intersection(router_name_set)
        update_formset = MultiPermissionFormSet(
            initial=[row for name, row in router_dict.items() if name in update_name_list])

    return render(
        request,
        'rbac/permission_batch.html',
        {
            'destroy_formset': destroy_formset,
            'update_formset': update_formset,
            'add_formset': add_formset,
        }
    )


def permission_auth(request):
    """权限分配"""
    uid = request.GET.get('uid')
    rid = request.GET.get('rid')

    if request.method == 'POST' and request.POST.get('postType') == 'role':
        # 更新选择用户所拥有的角色
        user = UserInfo.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        user.roles.set(request.POST.getlist('roles'))

    if request.method == 'POST' and request.POST.get('postType') == 'permission' and rid:
        role = Role.objects.filter(id=rid).first()
        if not role:
            return HttpResponse('角色不存在')
        role.permissions.set(request.POST.getlist('permissions'))

    users = UserInfo.objects.all()
    # ############################## 角色信息 ##########################
    # 当前用户拥有的角色
    user_has_roles = UserInfo.objects.filter(id=uid).values('id', 'roles')
    user_has_roles_dict = {item['roles']: None for item in user_has_roles}

    # 所有的角色
    roles = Role.objects.all()

    # ############################## 权限信息 ##########################
    all_menu_list = []

    if rid:
        role_has_permissions = Role.objects.filter(id=rid, permissions__id__isnull=False).values('id', 'permissions')
    elif uid and not rid:
        user = UserInfo.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        role_has_permissions = user.roles.filter(permissions__id__isnull=False).values('id', 'permissions')
    else:
        role_has_permissions = []

    role_has_permissions_dict = {item['permissions']: None for item in role_has_permissions}

    # 根权限
    root_permission = Permission.objects.filter(pid__isnull=True).values('id', 'title')
    root_permission_dict = {}
    for per in root_permission:
        per['children'] = []
        nid = per['id']
        root_permission_dict[nid] = per
        all_menu_list.append(per)

    # 子权限
    node_permission = Permission.objects.filter(pid__isnull=False).values('id', 'title', 'pid_id')
    for per in node_permission:
        pid = per['pid_id']
        root_permission_dict[pid]['children'].append(per)

    return render(
        request,
        'rbac/permission_auth.html',
        {
            'users': users,
            'roles': roles,
            'user_has_roles_dict': user_has_roles_dict,
            'role_has_permissions_dict': role_has_permissions_dict,
            'all_menu_list': all_menu_list,
            'uid': uid,
            'rid': rid
        }
    )


def role_list(request):
    """
    角色管理
    """
    form = RoleForm()
    if request.method == 'POST':
        form = RoleForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(reverse('rbac:role-list'))
    roles = Role.objects.all().order_by('-id')
    return render(request, 'rbac/role_list.html', {'roles': roles, 'form': form})


def role_edit(request, pk):
    """
    编辑角色
    :param request:
    :param pk:
    """
    obj = Role.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('角色不存在')
    if request.method == 'GET':
        form = RoleForm(instance=obj)
    else:
        form = RoleForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()

        return redirect(reverse('rbac:role-list'))

    roles = Role.objects.all().order_by('-id')
    return render(request, 'rbac/role_list.html', {'roles': roles, 'form': form})


def role_del(request, pk):
    """
    删除角色
    :param request:
    :param pk:
    """
    Role.objects.filter(id=pk).delete()
    return redirect(reverse('rbac:role-list'))

rbac/templates/rbac/permission_batch.html
{% extends 'rbac/base.html' %}{% load static rbac %}
{% block title %}批量处理权限{% endblock title %}
{% block right %}
    <div class="container-fluid mgt">
        <form method="post" action="?type=add">
            {% csrf_token %}
            {{ add_formset.management_form }}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-binoculars" aria-hidden="true"></i> 待新建权限列表
                    <button type="submit" class="right btn btn-success" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        新建
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：系统中自动发现且数据库中不存在的权限链接地址。
                </div>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>权限标题</th>
                        <th>链接地址</th>
                        <th>别名</th>
                        <th>父级权限</th>
                        <th>菜单</th>
                        <th>图标</th>
                        <th>排序</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in add_formset %}
                        <tr>
                            <td class="text-center">{{ forloop.counter }}</td>
                            {% for field in form %}
                                <td {% if forloop.first %} class="hide" {% endif %}>
                                    {% if field.field.is_checkbox %}
                                        <div class="checkbox text-center">
                                            <label>
                                                {{ field }}
                                            </label>
                                            <span class="text-danger">{{ field.errors.0 }}</span>
                                        </div>
                                    {% else %}
                                        {{ field }}<span class="text-danger">{{ field.errors.0 }}</span>
                                    {% endif %}

                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>

        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-th-list" aria-hidden="true"></i> 待删除权限列表
            </div>
            <div class="panel-body" style="color: #9d9d9d;">
                注意：数据库中存在，但系统中不存在的权限链接地址。
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>权限标题</th>
                    <th>链接地址</th>
                    <th>别名</th>
                    <th>父级权限</th>
                    <th>菜单</th>
                    <th>图标</th>
                    <th>排序</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for form in destroy_formset %}
                    <tr>
                    <td class="text-center">{{ forloop.counter }}</td>
                    {% for field in form %}
                        <td {% if forloop.first %} class="hide" {% endif %}>
                            {% if field.field.is_checkbox %}
                                <div class="checkbox text-center">
                                    <label>
                                        {{ field }}
                                        <span class="text-danger">{{ field.errors.0 }}</span>
                                    </label>
                                </div>
                            {% else %}
                                {{ field }}<span class="text-danger">{{ field.errors.0 }}</span>
                            {% endif %}
                        </td>
                    {% endfor %}
                    <td>
                        <a href="{% url 'rbac:permission-del' pk=form.initial.id %}" class="btn btn-xs btn-danger">
                            删除
                        </a>
                    </td>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <form method="post" action="?type=update">
            {% csrf_token %}
            {{ update_formset.management_form }}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-sitemap" aria-hidden="true"></i> 待更新权限列表
                    <button type="submit" class="right btn btn-success" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>更新
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：数据库和系统都存在的权限链接地址。
                </div>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>权限标题</th>
                        <th>链接地址</th>
                        <th>别名</th>
                        <th>父级权限</th>
                        <th>菜单</th>
                        <th>图标</th>
                        <th>排序</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in update_formset %}
                        <tr>
                        <td class="text-center">{{ forloop.counter }}</td>
                        {% for field in form %}
                            <td {% if forloop.first %} class="hide" {% endif %}>
                                {% if field.field.is_checkbox %}
                                    <div class="checkbox text-center">
                                        <label>
                                            {{ field }}
                                            <span class="text-danger">{{ field.errors.0 }}</span>
                                        </label>
                                    </div>
                                {% else %}
                                    {{ field }}<span class="text-danger">{{ field.errors.0 }}</span>
                                {% endif %}
                            </td>
                        {% endfor %}
                        <td>
                            {% if form.initial.id %}
                                <a href="{% url 'rbac:permission-del' pk=form.initial.id %}" class="btn btn-xs btn-danger">
                                    删除
                                </a>
                            {% else %}
                                <a href="{% url 'rbac:permission-del' pk=form.id.value %}" class="btn btn-xs btn-danger">
                                    删除
                                </a>
                            {% endif %}
                        </td>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>
    </div>
{% endblock right %}

rbac/templates/rbac/role_list.html
{% extends 'rbac/base.html' %}{% load static %}
{% block title %} 角色管理 {% endblock title %}
{% block css %}
    <style>
        .mgt{
           margin-top: 20px;
        }
        .panel-heading{
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            overflow: hidden;
        }
    </style>
{% endblock %}
{% block right %}
    <div class="row">
        <div class="container-fluid mgt">
            <div class="col-md-12">
                    <div class="panel">
                        <div class="panel-heading panel-heading-ex">
                            <form class="form-inline" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-control"  name="name" value="{{ form.name.value|default:'' }}" placeholder="请输入角色名称" required>
                                </div>
                                {% if form.name.value %}
                                    <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> 保存</button>
                                {% else %}
                                    <button type="submit" class="btn btn-success"><i class="fa fa-plus"></i> 添加</button>
                                {% endif %}
                            </form>
                        </div>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>角色名称</th>
                                <th>权限数量</th>
                                <th>选项</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for role in roles %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ role.name }}</td>
                                    <td>{{ role.permissions.count }}</td>
                                    <td>
                                        <a class="btn btn-xs btn-primary " href="{% url 'rbac:role-edit' pk=role.id %}">修改</a>
                                        <a class="btn  btn-xs btn-danger btn-del" href="#" data-item="{% url 'rbac:role-del' pk=role.id %}">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
            </div>
        </div>
    </div>
{% endblock %}

rbac/templates/rbac/user_list.html
{% extends 'rbac/base.html' %}{% load static rbac%}
{% block title %}用户信息{% endblock title %}
{% block css %}
    <style>

    </style>
{% endblock %}
{% block right %}
    <div class="row">
		<div class="container-fluid mgt">
            <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-md-2"><span class="panel-title h34">用户信息</span></div>
                                <div class="col-md-10">
                                    {% if request|has_permission:'rbac:user-add'%}
                                    <span class="right">
                                        <a class="btn btn-success" href="{% url 'rbac:user-add' %}">
                                            <i class="glyphicon glyphicon-plus">新建</i>
                                        </a>
                                    </span>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>登录名</th>
                                <th>姓名</th>
                                <th>性别</th>
                                <th>电话</th>
                                <th>类型</th>
                                <th>超级管理员</th>
                                <th>是否有效</th>
                                {% if request|has_permission:"rbac:user-edit" or  request|has_permission:"rbac:user-del"%}
                                    <th>选项</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for user in users %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ user.name }}</td>
                                    <td>{{ user.real_name }}</td>
                                    <td>{{ user.get_gender_display|default:"" }}</td>
                                    <td>{{ user.telephone }}</td>
                                    <td>{{ user.post }}</td>
                                    <td>{{  user.is_superuser|boolean_icon }}</td>
                                    <td>{{ user.is_active|boolean_icon }}</td>
                                    <td>
                                        {% if request|has_permission:"rbac:user-edit" %}
                                        <a class="btn btn-xs btn-primary" href="{% url 'rbac:user-edit' user.id %}">修改</a>
                                        {% endif %}
                                        {% if request|has_permission:"rbac:user-del" %}
                                        <a class="btn  btn-xs btn-danger btn-del" href="#" data-item="{% url 'rbac:user-del' user.id %}">删除</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
            </div>
		</div>
	</div>
{% endblock %}
{% block extjs %}
{#<script>#}
{#    $(function () {#}
{#        $(".btn-del").click(function(e){#}
{#            var url = $(this).attr("data-item");#}
{#            e.preventDefault();#}
{#            Swal.fire({#}
{#              title: '真的要删除吗?',#}
{#              text: "删除将无法恢复!",#}
{#              type: 'warning',#}
{#              showCancelButton: true,#}
{#              confirmButtonColor: '#3085d6',#}
{#              cancelButtonColor: '#d33',#}
{#              confirmButtonText: '确定删除',#}
{#              cancelButtonText: '取消'#}
{#            }).then((result) => {#}
{#              if (result.value) {#}
{#                   window.location.href =url#}
{##}
{#              }#}
{#            })#}
{##}
{#        })#}
{#    })#}
{#</script>#}
{% endblock extjs %}