adm/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from adm.views import (
    UserAuthView,
    UserCategoryListView,
    OfficeView,
    OfficeUpdateView,
    UserDetailChangeView,
    UserDetailView,
    MyCase,
    CaseCategory,
    CaseInfo,
    CaseDistributeView,
    CaseDoingListView,
    CaseSearchListView)

urlpatterns = [
    url(r'^user_auth/$', UserAuthView.as_view(), name="user-auth"),
    url(r'^user_category_list/$', UserCategoryListView.as_view(), name="user-category-list"),
    url(r'^user_detail_change/$', UserDetailChangeView.as_view(), name="user-detail-change"),
    url(r'^user_detail/(?P<pk>\d+)/$', UserDetailView.as_view(), name="user-detail"),
    url(r'^office/$', OfficeView.as_view(), name="office"),
    url(r'^office_update/(?P<pk>\d+)/$', OfficeUpdateView.as_view(), name="office-update"),

    url(r'^my_case/$', MyCase.as_view(), name="my-case"),
    url(r'^case_category/$', CaseCategory.as_view(), name="case-category"),

    url(r'^case_info/$', CaseInfo.as_view(), name="case-info"),
    url(r'^case_distrib_list/$', CaseDistributeView.as_view(), name="case-distrib-list"),
    url(r'^case_doing_list/$', CaseDoingListView.as_view(), name="case-doing-list"),
    url(r'^case_search_list/$', CaseSearchListView.as_view(), name="case-search-list"),

]

crimicivil/urls.py
from django.conf.urls import url, include

from crimicivil.views import CrmCivilCaseAddView, CrmCivilCaseDeleteView, CrmCivilCaseDetailView, \
    CrmCivilCaseUpdateView, CrmCivilCaseStageView, CrmCivilCaseDetailUpdateView, CrmCivilCaseDetailDeleteView, \
    CrmCivilCaseDetailSchemeView, CrmCivilCaseDetailListView, CrmCivilCaseDistribView

urlpatterns = [
    url(r'^crmcivil_add/$', CrmCivilCaseAddView.as_view(), name="crmcivil-case-add"),
    url(r'^crmcivil_del/(?P<crmcivil_id>\d+)/$', CrmCivilCaseDeleteView.as_view(), name="crmcivil-case-del"),
    url(r'^crmcivil_detail/(?P<crmcivil_id>\d+)/$', CrmCivilCaseDetailView.as_view(), name="crmcivil-case-detail"),
    url(r'^crmcivil_update/(?P<crmcivil_id>\d+)/$', CrmCivilCaseUpdateView.as_view(), name="crmcivil-case-update"),
    url(r'^crmcivil_stage/(?P<crmcivil_id>\d+)/$', CrmCivilCaseStageView.as_view(), name="crmcivil-case-stage"),
    url(r'^crmcivil_detail_update/(?P<detail_id>\d+)/$', CrmCivilCaseDetailUpdateView.as_view(), name="crmcivil-case-detail-update"),
    url(r'^crmcivil_detail_del/(?P<detail_id>\d+)/$', CrmCivilCaseDetailDeleteView.as_view(), name="crmcivil-case-detail-delete"),
    url(r'^crmcivil_detail_scheme/(?P<detail_id>\d+)/$', CrmCivilCaseDetailSchemeView.as_view(), name="crmcivil-case-detail-scheme"),
    url(r'^crmcivil_detail_list/(?P<detail_id>\d+)/$', CrmCivilCaseDetailListView.as_view(), name="crmcivil-case-detail-list"),
    url(r'^crmcivil_lawyer_distrib/(?P<crmcivil_id>\d+)/$', CrmCivilCaseDistribView.as_view(), name="crmcivil-lawyer-distrib"),

]

lawyer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.authtoken import views

from rbac.account import login, logout, password_change

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^password/change/(?P<pk>\d+)/$', password_change, name='password-change'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^api-token-auth/', views.obtain_auth_token, name="obtain-auth-token"),
    url(r'^rbac/', include('rbac.urls', namespace='rbac')),
    url(r'^adm/', include('adm.urls', namespace='adm')),
    url(r'^adm/api/', include('adm.api.urls')),
    url(r'^advisor/', include('advisor.urls', namespace='advisor')),
    url(r'^calculator/', include('calculator.urls', namespace='calculator')),
    url(r'^calculator/api/', include('calculator.api.urls', namespace='calculator-api')),
    url(r'^calc_manager/', include('calculator.calculator_urls', namespace='calc-mgr')),
    url(r'^civil/', include('civilcase.urls', namespace='civil-case')),
    url(r'^criminal/', include('crimicase.urls', namespace='criminal')),
    url(r'^admincase/', include('admincase.urls', namespace='admincase')),
    url(r'^private/', include('crimiprivate.urls', namespace='private')),
    url(r'^crmcivil/', include('crimicivil.urls', namespace='crmcivil')),
    url(r'^print/', include('civilcase.print_urls', namespace='print')),
    url(r'^civil/api/', include('civilcase.api.urls', namespace='civil-api')),
]

crimicivil/models.py
from decimal import Decimal

from django.db import models

from baseinfo.constants import *
from baseinfo.models import AgencyAuth, CivilLevel, CrmCivilLegalStatus
from civilcase.utils import money_num2word
from rbac.models import UserInfo

ORG_CC_LEGAL_STATUS = (
    (1, "原告"),
    (2, "被告人"),
)


class CrimiCivil(models.Model):
    """
    刑附民案件信息登记表
    """
    case_name = models.CharField(verbose_name="案件名称", max_length=240)
    info_type = models.IntegerField(verbose_name='信息类型',  default=1, choices=INFO_TYPE)
    case_prop = models.IntegerField(verbose_name="案件性质", choices=CASE_PROPERTY, default=0)
    agent = models.ForeignKey(AgencyAuth, verbose_name='代理权限', blank=True, null=True)
    org_legal_status = models.IntegerField(verbose_name="原审法律地位", choices=ORG_CC_LEGAL_STATUS, blank=True, null=True)
    stage = models.ForeignKey(CivilLevel, related_name="cc_stages", verbose_name='案件所处阶段',  limit_choices_to={'id__lt': 4})
    commission_stage = models.ManyToManyField(CivilLevel, verbose_name='委托阶段', blank=True,  limit_choices_to={'id__lt': 4})
    total_expenses = models.DecimalField(verbose_name="代理费", max_digits=9, decimal_places=2, default=0)
    case_brief = models.TextField(verbose_name="案由", blank=True, null=True)
    # 委托人信息(法人)
    cli_legal_name = models.CharField(verbose_name='公司名称', max_length=60, blank=True, null=True)
    cli_legal_person = models.CharField(verbose_name='法定代表人', max_length=32, blank=True, null=True)
    cli_legal_address = models.CharField(verbose_name='住所地', max_length=120, blank=True, null=True)
    cli_legal_tel = models.CharField(verbose_name='公司联系电话', max_length=120, blank=True, null=True)
    cli_legal_code = models.CharField(verbose_name='统一社会信用代码', max_length=64, blank=True, null=True)
    cli_legal_job = models.CharField(verbose_name='公司所处职务', max_length=32, blank=True, null=True)
    # 委托人信息(自然人)
    cli_name = models.CharField(verbose_name='委托人姓名', max_length=50, blank=True, null=True)
    cli_tel = models.CharField(verbose_name='委托人电话', max_length=50, blank=True, null=True)
    cli_relation = models.CharField(verbose_name='与当事人关系', max_length=50, blank=True, null=True)
    cli_address = models.CharField(verbose_name='住址', max_length=60, blank=True, null=True)
    cli_id_card = models.CharField(verbose_name='身份证号', max_length=50, blank=True, null=True)
    # 监护人
    guard_name = models.CharField(verbose_name='监护人姓名', max_length=30, blank=True, null=True)
    guard_tel = models.CharField(verbose_name='监护人电话', max_length=30, blank=True, null=True)
    guard_relation = models.CharField(verbose_name='与当事人关系', max_length=50, blank=True, )
    guard_address = models.CharField(verbose_name='住址', max_length=100, blank=True, null=True)
    guard_id_card = models.CharField(verbose_name='身份证号', max_length=50, blank=True, null=True)
    # 当事人信息(自然人)
    party_name = models.CharField(verbose_name='当事人姓名', max_length=50, blank=True, null=True)
    party_person_status = models.ForeignKey(CrmCivilLegalStatus, verbose_name="所处法律地位", related_name="cc_person_status", blank=True, null=True, on_delete=models.SET_NULL)
    party_sex = models.CharField(verbose_name='性别', max_length=20, choices=SEX_CHOICES,  blank=True, null=True)
    party_birth = models.DateField(verbose_name='出生日期', blank=True, null=True)
    party_nation = models.CharField(verbose_name='民族', max_length=10, blank=True, null=True)
    party_tel = models.CharField(verbose_name='联系电话', max_length=64, blank=True, null=True)
    party_id_code = models.CharField(verbose_name='身份证号', max_length=50, blank=True, null=True)
    party_address = models.CharField(verbose_name='住址', max_length=200, blank=True, null=True)
    party_job = models.CharField(verbose_name='职业', max_length=64, blank=True, null=True)
    # 当事人信息(法人信息)
    party_legal_name = models.CharField(verbose_name='公司名称', max_length=120, blank=True, null=True)
    party_company_status = models.ForeignKey(CrmCivilLegalStatus, verbose_name="所处法律地位", related_name="cc_company_status", blank=True, null=True,
                                           on_delete=models.SET_NULL)
    party_legal_person = models.CharField(verbose_name='法定代表人', max_length=32, blank=True, null=True)
    party_legal_job = models.CharField(verbose_name='职务', max_length=50, blank=True, null=True)
    party_legal_address = models.CharField(verbose_name='住所地', max_length=200, blank=True, null=True)
    party_legal_telephone = models.CharField(verbose_name='联系电话', max_length=32, blank=True, null=True)
    party_legal_code = models.CharField(verbose_name='统一社会信用代码', max_length=30, blank=True, null=True)
    # 分配律师
    lawyer = models.ForeignKey(UserInfo, verbose_name='主办律师', related_name="cc_lawyers", blank=True, null=True, on_delete=models.SET_NULL)
    assist = models.ForeignKey(UserInfo, verbose_name='辅助律师', related_name="cc_assists", blank=True, null=True,
                               on_delete=models.SET_NULL)
    manager = models.ForeignKey(UserInfo, verbose_name='客户经理', related_name="cc_managers", blank=True, null=True,
                                on_delete=models.SET_NULL)
    is_assign = models.IntegerField(verbose_name="分配确认", choices=IS_ASSIGN, blank=True, null=True,)
    user = models.ForeignKey(UserInfo, verbose_name=u'录入人', blank=True, null=True, on_delete=models.SET_NULL)
    update_at = models.DateTimeField(verbose_name="修改时间", auto_now=True)
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        verbose_name = '刑附民案件登记'
        verbose_name_plural = verbose_name
        ordering = ['-create_at']

    def __str__(self):
        return self.case_name

    def get_cli_name(self):
        return self.cli_name if self.cli_name else self.cli_legal_name

    def get_party_name(self):
        return self.party_name if self.party_name else self.party_legal_name

    def get_cli_telephone(self):
        return self.cli_tel if self.cli_tel else self.cli_legal_tel

    def get_party_telephone(self):
        return self.party_tel if self.party_tel else self.party_legal_telephone

    def get_commission_stage(self):
        commi_stage = []
        for item in self.commission_stage.all():
            commi_stage.append(item.name)
        return ",".join(commi_stage)

    def get_total_expenses(self):
        return money_num2word(float(self.total_expenses))

    def get_birth_date(self):
        return self.create_at.year - self.party_birth.year


class CrimiCivilHisResult(models.Model):
    """刑附民历史判决结果"""
    MANNER = (
        (0, '接受'),
        (1, '不服'),
    )
    crimicivil = models.ForeignKey(CrimiCivil, verbose_name='案件名称', on_delete=models.CASCADE)
    legal_status = models.ForeignKey(CrmCivilLegalStatus, verbose_name="法律地位", on_delete=models.SET_NULL, null=True)
    stage = models.ForeignKey(CivilLevel, verbose_name='案件阶段', limit_choices_to={'id__lt': 4})
    court_name = models.CharField(verbose_name='法院名称', max_length=50, blank=True, null=True)
    judge_date = models.DateField(verbose_name='判决时间', max_length=20, blank=True, null=True)
    judge_code = models.CharField(verbose_name='判决编号', max_length=50, blank=True, null=True)
    judge_result = models.IntegerField(verbose_name='判决结果', choices=JUDGE_RESULT)
    judge_manner = models.IntegerField(verbose_name='是否接受', default=0, choices=MANNER)
    update_at = models.DateTimeField(verbose_name="修改时间", auto_now=True)
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        verbose_name = '刑附民历史判决'
        verbose_name_plural = verbose_name
        ordering = ["stage"]

    def __str__(self):
        return "{}({})".format(self.crimicivil.case_name, self.stage.name)


class CrimiCivilDetail(models.Model):
    """刑附民案件具体执行情况"""
    STATUS = (
        (0, '未完'),
        (1, '完毕'),
    )
    DISTRIB = (
        (0, '未分配'),
        (1, '已分配'),
    )
    crimicivil = models.ForeignKey(CrimiCivil, verbose_name='案件名称', on_delete=models.CASCADE)
    legal_status = models.ForeignKey(CrmCivilLegalStatus, verbose_name="所处法律地位", on_delete=models.SET_NULL, null=True)
    stage = models.ForeignKey(CivilLevel, verbose_name='案件所处阶段', limit_choices_to={'id__lt': 4})
    court_name = models.CharField(verbose_name='法院名称', max_length=50, blank=True, null=True)
    court_tel = models.CharField(verbose_name='法院电话', max_length=30, blank=True, null=True)
    court_judge = models.CharField(verbose_name='法院法官', max_length=20, blank=True, null=True)
    judge_date = models.DateField(verbose_name='判决时间', max_length=20, blank=True, null=True)
    judge_code = models.CharField(verbose_name='判决编号', max_length=50, blank=True, null=True)
    judge_result = models.IntegerField(verbose_name='判决结果', choices=JUDGE_RESULT)
    status = models.IntegerField(verbose_name="案件状态", choices=STATUS, default=0)
    update_at = models.DateTimeField(verbose_name="修改时间", auto_now=True)
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        verbose_name = '刑附民案件执行'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{}({})".format(self.crimicivil.case_name, self.stage.name)

    def get_relative_person(self):
        natures = self.natures.exclude(legal_status=7)
        legals = self.legals.exclude(legal_status=7)
        relative_person = []
        for n in natures:
            relative_person.append(n.name)

        for l in legals:
            relative_person.append(l.company_name)

        return ",".join(relative_person)

    def get_relative_count(self):
        nature_count = self.natures.count()
        legals_count = self.legals.count()
        return nature_count + legals_count


class CrimiCivilNaturePerson(models.Model):
    """刑附民自然人信息"""
    case = models.ForeignKey(CrimiCivilDetail, verbose_name='案件名称', related_name="natures", null=True, blank=True, on_delete=models.CASCADE,)
    name = models.CharField(verbose_name='姓名', max_length=50)

crimicivil/templates/crimicivil/print/crmcv_appeal.html
{% extends 'civilcase/print/print_base.html' %}{% load static%}
{% block title %}上诉状{% endblock title %}
{% block css %}
  <style>
    @page {
        size:a4 portrait;
        margin: 2.5cm;
    }

    .table {
        border: 0px solid black;
        border-collapse: collapse;
        padding-top: 3px;
        font-size:15pt;
        font-family: 宋体;
        width:100%;
    }
    .table td{
        height: 25px;
        word-wrap:break-word;
        word-break:break-all;
        border: 0px!important;
    }
    div{
        line-height: 30px;
    }
    span{
        display:block;
        text-indent: 2.2rem;
        line-height: 30px;
    }
    .table .td_h{
        height: 140px;
    }
    .table .td_50{
        height:50px;
    }
    .table .td_20{
        height:20px;
    }
    .td_right{
        text-align: right;
        padding-right:40px;
    }
 </style>
{% endblock %}
{% block print_content %}
<div class="print_area" id="print_page">
    <table class="table">
        <caption style="text-align: center; padding-bottom: 30px;"><h1>上诉状</h1></caption>
        <tbody>
        {% if civil_detail.civil.party_name %}
            <tr>
                <td>上诉人{% if first_trial %}(原审{{ first_trial.legal_status.name }}){% endif %}:{{ civil_detail.civil.party_name }}</td>
                <td>性别: {{ civil_detail.civil.get_party_sex_display }}</td>
                <td>民族：{{ civil_detail.civil.party_nation }}</td>
                <td>年龄: {{ civil_detail.civil.get_birth_date }}</td>
            </tr>
            <tr>
                <td colspan="2">身份证号: {{ civil_detail.civil.party_id_code }}</td>
                <td colspan="2">电话: {{ civil_detail.civil.party_tel }}</td>
            </tr>
            <tr>
                <td colspan="4">现住址: {{ civil_detail.civil.party_address }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">上诉人{% if first_trial %}(原审{{ first_trial.legal_status.name }}){% endif %}：{{ civil_detail.civil.party_legal_name }}</td>
            </tr>
            <tr>
                <td colspan="4">社会统一信用代码: {{ civil_detail.civil.party_legal_code }}</td>
            </tr>
            <tr>
                <td colspan="2">法定代表人: {{ civil_detail.civil.party_legal_person }}</td>
                <td colspan="2">联系电话: {{ civil_detail.civil.party_legal_telephone }}</td>
            </tr>
            <tr>
                <td colspan="4">住所地:{{ civil_detail.civil.party_legal_address }}</td>
            </tr>
        {% endif %}
        {% for nature in natures %}
            <tr>
                <td>被上诉人{% if relative_legal_status %}(原审{{ relative_legal_status.name }}){% endif %}:{{ nature.name }}</td>
                <td>性别: {{ nature.get_gender_display }}</td>
                <td>民族：{{ nature.nation }}</td>
                <td>年龄: {{ nature.age }}</td>
            </tr>
            <tr>
                <td colspan="4">电话: {{ nature.tel }}</td>
            </tr>
            <tr>
                <td colspan="4">现住址: {{ nature.address }}</td>
            </tr>
        {% endfor %}
        {% for legal in legals %}
            <tr>
                <td colspan="4">被上诉人{% if relative_legal_status %}(原审{{ relative_legal_status.name }}){% endif %}
                    :{{ legal.company_name }}</td>
            </tr>
            <tr>
                <td colspan="4">社会统一信用代码: {{ legal.credit_code }}</td>
            </tr>
            <tr>
                <td colspan="2">法定代表人: {{ legal.legal_person }}</td>
                <td colspan="2">联系电话: {{ legal.telephone }}</td>
            </tr>
            <tr>
                <td colspan="4">住所地:{{ legal.address }}</td>
            </tr>
        {% endfor %}
            <tr>
                <td colspan="4">
                    <span>上诉人因不服{{ first_trial.court_name }}作出的（{{ first_trial.judge_code }}）判决，现依法提起上诉。</span>
                </td>
            </tr>
            <tr>
                <td colspan="4"><div>上诉请求:</div></td>
            </tr>
            <tr>
                <td colspan="4"><span>{{ civil_detail.civillawsuitscheme.appeal_claim|safe }}</span></td>
            </tr>
            <tr>
                <td colspan="4">
                    <div>事实和理由:</div>
                </td>
            </tr>
            <tr>
                <td colspan="4"><span>{{ civil_detail.civillawsuitscheme.appeal_reasons|safe }}</span></td>
            </tr>
            <tr>
                <td colspan="4" class="td_20"></td>
            </tr>
            <tr>
                <td colspan="4"><span>此致</span></td>
            </tr>
            <tr>
                <td colspan="4">
                    <div>{{ civil_detail.court_name }}</div>
                </td>
            </tr>
            <tr>
                <td colspan="4" class="td_50"></td>
            </tr>
            <tr>
                <td colspan="4" class="td_right"><div style="padding-right:40px;">上诉人：</div></td>
            </tr>
            <tr>
                <td colspan="4" class="td_right"><div>{% now 'Y年m月d日' %}</div></td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

crimicivil/templates/crimicivil/print/crmcv_application.html
{% extends 'civilcase/print/print_base.html' %}{% load static%}
{% block title %}相关申请书{% endblock title %}
{% block css %}
    <style type="text/css">
        @page {
            size: a4 ;
            margin-left: 2.5cm;
        }

        .table {
            border-collapse: collapse;
            width: 100%;
            font-family: 宋体;
            font-size: 15pt;
            margin: 0 auto;
        }

        .table,
        td,
        th {
            border: 1px solid black !important;
            text-align: center;
            height: 35px;
            padding: 5px;
        }

        .td_10 {
            width: 8%;
        }

        .td_20 {
            width: 15%
        }

        caption {
            text-align: center;
            color: #000;
        }

        .left {
            text-align: left;
        }
    </style>
{% endblock %}
{% block print_content %}
    <table class="table" id="print_page">
        <caption><h1>相关申请书</h1></caption>
        <thead>
        <tr>
            <th class="td_10">序号</th>
            <th>相关申请书</th>
        </tr>
        </thead>
        <tbody>
        {% for a in applications %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td class="left">{{ a.appli_name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

crimicivil/templates/crimicivil/print/crmcv_complaint.html
{% extends 'civilcase/print/print_base.html' %}{% load static%}
{% block title %}起诉状{% endblock title %}
{% block css %}
    <style>
        @page {
            size: a4 portrait;
            margin: 2.5cm;

        }
        .table {
            border: 0px;
            border-collapse: collapse;
            padding-top: 3px;
            font-size: 15pt;
            font-family: 宋体;
            width: 100%;
        }

        .table td {
            height: 25px;
            word-wrap: break-word;
            word-break: break-all;
            border: 0px!important;
            padding-top: 5px!important;
            padding-bottom: 5px!important;
        }

        div {
            line-height: 25px;
        }

        span {
            display: block;
            text-indent: 2.2rem;
            line-height: 25px;
        }

        .table .td_h {
            height: 140px;
        }

        .table .td_50 {
            height: 50px;
        }

        .table .td_20 {
            height: 20px;
        }

        .td_right {
            text-align: right;
            padding-right: 40px;
        }

        .sp_h {
            min-height: 100px;
        }
    </style>
{% endblock css %}
{% block print_content %}
    <table class="table" id="print_page">
        <caption style="text-align: center">
            <h1>起诉状</h1>
        </caption>
        <tbody>
        {% if crmcivil_detail.crimicivil.party_name %}
            <tr>
                <td>原告:{{ crmcivil_detail.crimicivil.party_name }}</td>
                <td>性别: {{ crmcivil_detail.crimicivil.get_party_sex_display }}</td>
                <td>民族：{{ crmcivil_detail.crimicivil.party_nation }}</td>
                <td>年龄: {{ crmcivil_detail.crimicivil.get_birth_date }}</td>
            </tr>
            <tr>
                <td colspan="2">身份证号: {{ crmcivil_detail.crimicivil.party_id_code }}</td>
                <td colspan="2">电话: {{ crmcivil_detail.crimicivil.party_tel }}</td>
            </tr>
            <tr>
                <td colspan="4">现住址: {{ crmcivil_detail.crimicivil.party_address }}</td>
            </tr>
            {% if crmcivil_detail.crimicivil.guard_name %}
                <tr>
                    <td colspan="2">法定代理人:{{ crmcivil_detail.crimicivil.guard_name }}({{ crmcivil_detail.crimicivil.guard_relation }})
                    </td>
                    <td colspan="2">电话: {{ crmcivil_detail.crimicivil.guard_tel }}</td>
                </tr>
                <tr>
                    <td colspan="4">现住址: {{ crmcivil_detail.crimicivil.guard_address }}</td>
                </tr>
            {% endif %}
            <tr>
                <td colspan="4" class="td_20"></td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">原告：{{ crmcivil_detail.crimicivil.party_legal_name }}</td>
            </tr>
            <tr>
                <td colspan="4">社会统一信用代码: {{ crmcivil_detail.crimicivil.party_legal_code }}</td>
            </tr>
            <tr>
                <td colspan="2">法定代表人: {{ crmcivil_detail.crimicivil.party_legal_person }}</td>
                <td colspan="2">联系电话: {{ crmcivil_detail.crimicivil.party_legal_telephone }}</td>
            </tr>
            <tr>
                <td colspan="4">住所地:{{ crmcivil_detail.crimicivil.party_legal_address }}</td>
            </tr>
        {% endif %}
        {% for nature in natures %}
            <tr>
                <td>被告: {{ nature.name|default:"" }}</td>
                <td>性别: {{ nature.get_gender_display }}</td>
                <td>民族：{{ nature.nation|default:"" }}</td>
                <td>年龄: {{ nature.age|default:"" }}</td>
            </tr>
            <tr>
                <td colspan="2">身份证号: {{ nature.id_code|default:"" }}</td>
                <td colspan="2">电话: {{ nature.tel|default:"" }}</td>
            </tr>
            <tr>
                <td colspan="4">现住址: {{ nature.address|default:"" }}</td>
            </tr>
        {% endfor %}
        {% for legal in legals %}
            <tr>
                <td colspan="4">被告：{{ legal.company_name|default:"" }}</td>
            </tr>
            <tr>
                <td colspan="4">社会统一信用代码: {{ legal.credit_code|default:"" }}</td>
            </tr>
            <tr>
                <td colspan="2">法定代表人: {{ legal.legal_person|default:"" }}</td>
                <td colspan="2">联系电话: {{ legal.telephone|default:"" }}</td>
            </tr>
            <tr>
                <td colspan="4">住所地: {{ legal.address|default:"" }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="4">
                <div>诉讼请求:</div>
            </td>
        </tr>
        <tr>
            <td colspan="4"><span class="sp_h">{{ crmcivil_detail.crimicivillawsuitscheme.complaint_claim|safe }}</span>
            </td>
        </tr>
        <tr>
            <td colspan="4">
                <div>事实和理由:</div>
            </td>
        </tr>
        <tr>
            <td colspan="4"><span class="sp_h">{{ crmcivil_detail.crimicivillawsuitscheme.complaint_reasons|safe }}</span>
            </td>
        </tr>
        <tr>
            <td colspan="4" class="td_20"></td>
        </tr>
        <tr>
            <td colspan="4"><span>此致</span></td>
        </tr>
        <tr>
            <td colspan="4">
                <div>{{ civil_detail.court_name }}</div>
            </td>
        </tr>

        <tr>
            <td colspan="4" class="td_right">
                <div>起诉人：{{ crmcivil_detail.crimicivil.get_party_name }}</div>
            </td>
        </tr>
        <tr>
            <td colspan="4" class="td_right">
                <div>{% now 'Y年m月d日' %}</div>
            </td>
        </tr>
        </tbody>
    </table>
{% endblock %}